version: '3.4'

services:
  phoenix:
    image: phoenix
    build:
      context: deps/phoenix
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./priv/static/phoenix.js"]
